### ISSUE TITLE
Add install_requires and review setup_requires in setup.py

### ISSUE THREAD

**Issue by AlexHagerman** [pymssql/pymssql#582]
Setup.py currently contains tests and setup requires, but not install requires. `setup_requires` also doesn't contain Cython. We don't have a requirements file provided either. I believe we need to review the Cython dependency and if it belongs in setup or install requires to make sure it is made available when people use tools such as tox.

https://setuptools.readthedocs.io/en/latest/setuptools.html
https://packaging.python.org/discussions/install-requires-vs-requirements/

ref #578

**Comment by adriannye** [comment]
I tried both separately and then together and it didn't make any difference, I still see issue #578.

**Comment by ermakov-oleg** [comment]
Maybe we need to use `pyproject. toml` from https://www.python.org/dev/peps/pep-0518/ to install build dependencies like Cython?

`pyproject. toml`
```toml
[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel", "Cython"]
```
